# -*- coding: utf-8 -*-
"""plotting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnotEex6uEt-aZ4LRD-1d_Yb3WiJ3BwY
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.array([1,2,3,4,5])
y=np.array([2,3,5,4,6])

coefficents=np.polyfit(x,y,2)
polynomial = np.poly1d(coefficents)

x_fit=np.linspace(1,5,)
y_fit=polynomial(x_fit)

plt.scatter(x,y,color='red', label= 'my data points')
plt.plot(x_fit,y_fit ,  label= 'fitted polynomial')
plt.xlabel('x axis')
plt .ylabel('y axis')
plt.legend()
plt.show()